#!/usr/bin/python
"""
Usage:
  pomodoro [options] [<minutes>]
  pomodoro [options] analyse 

Options:
  -h --help                Show this screen.
  -n --with-network           Use this to keep the network active during the tomato
  --player=<musicplayer>   Set this to banshee or rythmbox to pause music 
  -l LOGFILE --logfile=LOGFILE      TSV file to store list of tomato sessions 
                               [default: /home/cpbl/personal/pomodoro-log.txt]

 This is a simple, customisable "Pomodoro Method" or "Tomato method" timer for facilitating high-focus work. 
 It turns off your music and network for work periods, traditionally for 25 minutes at a time, and suggests a five minute break in between the work sessions.
 Completed sessions are logged in a flexible, text-based log so you can do whatever you want (or nothing) with them. Whenever you finish a pomodoro, you can list any relevant tags to describe your work.

 It runs some custom command line strings at the beginning and end of each tomato, for instance to block access to certain websites by interfering with /etc/hosts.
 With the current settings, these sites are only unblocked at the end of the tomato, if the time is not during the 09h-17h workday (I work weekends :) )

 It also works with one of a couple of music players on GNU/Linux so that any music that's playing when you start is paused and continues after you've logged your session.
  
"""
import docopt,os,sys,datetime,subprocess
import commands # Linux 
import pandas as pd

def start_session(arguments):
    workMinutes= arguments['<minutes>'] or '25'  # Implements default value for a positional argument in docopts
    LOGFILE=arguments['--logfile']
    networking=arguments['--with-network']
    musicPlayer=arguments['--player']
    BLOCK_WEB_SITES='cp /home/local/etc/hosts-focus /etc/hosts'
    UNBLOCK_WEB_SITES='cp /home/local/etc/hosts-lax /etc/hosts'
    
    #if workMinutes is None:
    #    workMinutes =25
    workMinutes =int(workMinutes)
    os.system('echo "Starting Pomodoro for '+str(workMinutes)+' minutes at `date` ..."')
    os.system("""
    nmcli networking off
    echo "Networking off."
    """*(not networking)+"""
    notify-send "Starting Pomodoro for $workMinutes minutes at `date`.   Networking """+{True:'left on',False:'off'}[networking]+"""."

    """+BLOCK_WEB_SITES+"""

    """)

    # We will mute all sound. But it's nicer, if we can, to pause music where it was:
    musicPlayers=['rhythmbox','banshee'] if musicPlayer is None else [musicPlayer]
    musicPlayers= [mp for mp in musicPlayers if commands.getstatusoutput('echo $(pidof '+mp+')')[1]]
    print('Found alive music player(s): '+(str(musicPlayers) if musicPlayers else 'None'))
    # Now eliminate those that are not actually playing (if we know how to check):
    musicPlayers= [mp for mp in musicPlayers if (not mp=='banshee' or 'playing' in commands.getstatusoutput("banshee --query-current-state")[1])]
    print('   Pausing playing music player(s): '+(str(musicPlayers) if musicPlayers else 'None'))    
    # Now pause those that we know how to pause:
    if 'banshee' in musicPlayers:
        os.system("banshee --pause")
    if 'rhythmbox' in musicPlayers:
        os.system("rhythmbox-client --pause")

        
    hour=datetime.datetime.now().hour
    shdo="""
    # Regardless of pausing play, mute all sounds:
    amixer -q -D pulse sset Master mute
    sleep $((60*"""+str(workMinutes)+"""))
    notify-send "Break!"
    """+ (not networking)* """ 
    nmcli networking on 
    echo "      Networking on!"
    """+         """

    H=$(date +%H)
    """+ (hour<9 or hour>=17)*UNBLOCK_WEB_SITES +"""

    # In-place edit: add a line to the beginning of the file
    sed -i -e "1i`date`	"""+str(workMinutes)+"""	"'\' """+LOGFILE+"""
    echo "Enter any tags and quit emacs..."
    emacs """+LOGFILE+"""
    # Add a newline, and remove any double new lines:
    echo >> """+LOGFILE+"""
    # In-place edit: remove double newlines
    sed -i '/^[ \t]*$/d' """+LOGFILE+""" 
    # Regardless of restarting play, un-mute all sounds:
    amixer -q -D pulse sset Master unmute
    echo "Starting 5 minutes break at `date` ..."
    """
    # Now un-pause those that we believe were playing:
    if 'banshee' in musicPlayers:
        shdo+="banshee --play\n"
    if 'rhythmbox' in musicPlayers and 0:
        shdo+="rhythmbox-client --play\n"
    shdo+="""
    sleep 300 && notify-send "Start a new work cycle!"
    echo "Finished break.   Restart me for another work cycle."
    """
    #print(shdo)
    os.system(shdo)

def get_pid(process_name, contains=True):
    """ Quasi-cross platform way to find if something is running."""
    ffff=sorted([ss.name() for ss in psutil.process_iter()])
    print ffff
    fuck
    for proc in psutil.process_iter():
        if 'ansh' in proc.name(): print proc.name() 
        if proc.name() == process_name or contains* (process_name.lower() in proc.name().lower()):
            return(proc)
    
def analyse_log(logfile):
    df=pd.read_table(logfile, names=['start','minutes','tags'])
    foiuew

################################################################################################
################################################################################################
################################################################################################
if __name__ == '__main__':
################################################################################################
################################################################################################
################################################################################################
# Docopt is a library for parsing command line arguments
    arguments = docopt.docopt(__doc__)
    workMinutes= arguments['<minutes>']

    import psutil
    if workMinutes in ['analyse','analyze']:
        analyse_log(arguments['--logfile'])
    else:
        start_session(arguments)
    pass

